carScreenSamples = [
    "cho mình hỏi giá màn hình cam 360",
    "màn hình 360 giá sau bạn",
    "màn hình giá bnh shop",
    "màn hình bao nhiêu tiền vậy shop",
    "màn liền camera 360 giá bn ạ",
    "màn hình giá sao",
    "xin giá màn liền cam 360",
    "xin giá màn hình",
    "giá màn hình shop",
    "gia man hinh shop",
    "giá màn bn ạ",
    "dc h500 bn",
    "tư vấn màn hình 360",
    "cho mình thông tin màn hình cam 360",
    "tư vấn màn liền cam 360",
    "màn hình có tính năng gì shop",
    "xin thông tin màn hình",
    "tư vấn man hinh shop",
    "màn hình phù hợp với vios ạ",
    "lắp đặt màn hình",
    "lắp cho xe kia carens 2013 đc ko.mjh tự lắp đc ko shop",
    "lắp cho ertiga 2022",
    "inova 2015 sài được ko",
    "e muốn lắp màn cho city rs 2025 ạ",
    "màn hình dctech có gì khác biệt so với màn hình android thông thường?",
    "dctech h500 có tích hợp được camera 360 không?",
    "giao diện màn hình dctech có gì nổi bật?",
    "giá màn hình dctech là bao nhiêu?",
    "màn hình dctech là gì vậy em?",
    "màn hình này có khác gì các loại khác trên thị trường không em?",
    "dctech có những dòng màn hình nào? Em tư vấn giúp dòng nào phù hợp với xe anh?",
    "phân tích dòng sản phẩm dctech h500 series?",
    "phân tích dòng sản phẩm dctech H300 Series?",
    "thông tin màn hình DC H500 Luxury",
    "dctech có những dòng màn hình nào?",
    "có những dòng màn hình nào",
    "có màn hình gì",
]

androidBoxSamples = [
    "android box giá sau bạn",
    "cho mình hỏi giá android box",
    "xin giá android box",
    "android box giá bnh shop",
    "xin giá android box",
    "giá android box shop",
    "tư vấn android box",
    "cho mình thông tin android box",
    "tư vấn android box",
    "android box có tính năng gì shop",
    "xin thông tin android box",
    "tư vấn android box shop",
    "android box cho xe có dùng được cho màn hình zin cx5 2025 k",
    "android box dc b300 có dùng đc cho vf9 không shop",
    "mercedes c200 2015 có dùng được ko?",
    "DCTECH đang có mẫu Android Box nào?",
    "Android Box DCTECH là gì? Dùng để làm gì?",
    "Box DCTECH có cần tháo màn hình không?",
    "Xe nào dùng được Android Box DCTECH vậy?",
    "Box có điều khiển giọng nói được không?",
    "Lắp Box có ảnh hưởng bảo hành xe không?",
    "Android Box có sử dụng được CarPlay không?",
    "Android Box DC B300 có mạnh không? Chạy có mượt không?",
]

camera360Samples = [
    "camera 360 giá sau bạn",
    "cho mình hỏi giá camera 360",
    "xin giá camera 360",
    "camera 360 giá bnh shop",
    "xin giá camera 360",
    "giá camera 360 shop",
    "Camera 360 DCTECH giá bao nhiêu?",
    "Góc quay camera có rộng không?",
    "Thời gian lắp đặt camera 360 mất bao lâu?",
    "Lái xe số sàn có cần camera 360 không em?",
    "Camera 360 có quay được ban đêm không?",
    "Camera DCTECH dùng được với màn hình nào?",
    "Camera 360 lắp lên có ảnh hưởng điện xe không?",
    "tư vấn camera 360",
    "cho mình thông tin camera 360",
    "tư vấn camera 360",
    "camera 360 có tính năng gì shop",
    "xin thông tin camera 360",
    "tư vấn camera 360 shop",
    "camera 360 cho xe có dùng được cho màn hình zin cx5 2025 k",
    "camera 360 dc b300 có dùng đc cho vf9 không shop",
    "mercedes c200 2015 có dùng được camera 360 ko?",
]

brandInfoSamples = [
    "DCTECH là gì vậy em?",
    "DCTECH có những dòng sản phẩm nào?",
    "DCTECH có cửa hàng ở đâu vậy em?",
    "DCTECH có hỗ trợ lắp đặt không?",
    "DCTECH có bảo hành không?",
    "DCTECH có hỗ trợ trả góp không?",
    "DCTECH có hỗ trợ lắp đặt tận nơi không?",
    "DCTECH có hỗ trợ lắp đặt ở tỉnh không?",
    "Chinh sách bảo hành của DCTECH như thế nào?",
    "DCTECH có những ưu đãi gì không?",
    "DCTECH có hỗ trợ kỹ thuật sau khi lắp đặt không?",   
]   



clarifySamples = [
    "Xin giá",
    "Xin gia",
    "Xin giá shop",
    "Giá",
    "Giá chính sác bao nhiêu",
    "Báo giá",
    "Báo giá sản phẩm",
    "bn",
    "giá bn",
    "giá bn v ạ",
    "gia nhiu vay",
    "giá sản phẩm",
    "cho xinh giá",
    "cho xin giá",
    "Xin giá sp",
    "giá thế nào shop",
    "giá sao a",
    "Cho mình xin giá tham khảo",
    "xin chào",
    "xin chào shop",
]