carScreenSamples = [
    "xin giá màn hình",
    "xin giá màn hình h500 premium",
    "xin giá màn hình h500 luxury",
    "xin giá màn hình h300 base",
    "xin giá màn hình h300 ultra",
    "màn hình h500 premium",
    "màn hình h500 luxury",
    "màn hình h300 base",
    "màn hình h300 ultra",
    "màn hình h500",
    "màn hình h300",
    "h500",
    "h500 premium",
    "h500 luxury",
    "h300",
    "h300 base",
    "h300 ultra",
    "giá màn hình shop",
    "giá màn bn ạ",
    "dc h500 bn",
    "cho mình hỏi giá màn hình tích hợp cam 360",
    "màn hình giá bnh shop",
    "màn hình bao nhiêu tiền vậy shop",
    "màn liền camera 360 giá bn ạ",
    "màn hình giá sao",
    "xin giá màn liền cam 360",
    "tư vấn màn hình 360",
    "cho mình thông tin màn hình cam 360",
    "tư vấn màn liền cam 360",
    "màn hình có tính năng gì shop",
    "xin thông tin màn hình",
    "tư vấn man hinh shop",
    "màn hình phù hợp với vios ạ",
    "lắp đặt màn hình",
    "lắp cho xe kia carens 2013 đc ko.mjh tự lắp đc ko shop",
    "lắp cho ertiga 2022",
    "inova 2015 sài được ko",
    "e muốn lắp màn cho city rs 2025 ạ",
    "màn hình dctech có gì khác biệt so với màn hình android thông thường?",
    "dctech h500 có tích hợp được camera 360 không?",
    "giao diện màn hình dctech có gì nổi bật?",
    "giá màn hình dctech là bao nhiêu?",
    "màn hình dctech là gì vậy em?",
    "màn hình này có khác gì các loại khác trên thị trường không em?",
    "dctech có những dòng màn hình nào? Em tư vấn giúp dòng nào phù hợp với xe anh?",
    "phân tích dòng sản phẩm dctech h500 series?",
    "phân tích dòng sản phẩm dctech H300 Series?",
    "thông tin màn hình DC H500 Luxury",
    "dctech có những dòng màn hình nào?",
    "có những dòng màn hình nào",
    "có màn hình gì",
    "Nếu giá màn hình tính thêm công lắp đặt thì bao nhiêu?",
    "Thông tin màn hình DC H500 Luxury",
    "Phân tích dòng sản phẩm DCTECH H300 Series?",
    "Phân tích dòng sản phẩm DCTECH H500 Series?",
    "Sao thấy nhiều loại màn hình quá...?",
    "Màn hình này có khác gì các loại khác trên thị trường không em?",
    "Màn hình DCTECH là gì vậy em?",
    "Giao diện màn hình DCTECH có gì nổi bật?",
    "DCTECH H500 có tích hợp được camera 360 không?",
    "Màn hình DCTECH có gì khác biệt so với màn hình Android thông thường?",
    "Màn hình ô tô"
]

androidBoxSamples = [
    "android box giá sau bạn",
    "cho mình hỏi giá android box",
    "xin giá android box",
    "android box",
    "xin giá dc b300",
    "xin giá b300",
    "b300",
    "dc b300",
    "android box giá bnh shop",
    "xin giá android box",
    "giá android box shop",
    "tư vấn android box",
    "cho mình thông tin android box",
    "tư vấn android box",
    "android box có tính năng gì shop",
    "xin thông tin android box",
    "tư vấn android box shop",
    "android box cho xe có dùng được cho màn hình zin cx5 2025 k",
    "android box dc b300 có dùng đc cho vf9 không shop",
    "mercedes c200 2015 có dùng được ko?",
    "DCTECH đang có mẫu Android Box nào?",
    "Android Box DCTECH là gì? Dùng để làm gì?",
    "Box DCTECH có cần tháo màn hình không?",
    "Xe nào dùng được Android Box DCTECH vậy?",
    "Box có điều khiển giọng nói được không?",
    "Lắp Box có ảnh hưởng bảo hành xe không?",
    "Android Box có sử dụng được CarPlay không?",
    "Android Box DC B300 có mạnh không? Chạy có mượt không?",
    "Android Box DC B300 có mạnh không? Chạy có mượt không?",
    "Android Box có sử dụng được CarPlay không?",
    "Lắp Box có ảnh hưởng bảo hành xe không?",
    "Box có điều khiển giọng nói được không?",
    "Xe nào dùng được Android Box DCTECH vậy?",
    "Box DCTECH có cần tháo màn hình không?",
    "Android Box DCTECH là gì? Dùng để làm gì?",
    "DCTECH đang có mẫu Android Box nào?"
]

camera360Samples = [
    "giá protech 5",
    "giá protech 6",
    "giá protech 7",
    "giá protech 10",
    "protech 5",
    "protech 6",
    "protech 7",
    "protech 10",
    "Cho anh xin giá protech 5",
    "Cho anh xin giá protech 6",
    "Cho anh xin giá protech 7",
    "Cho anh xin giá protech 10",
    "camera 360 protech 5",
    "camera 360 protech 6",
    "camera 360 protech 7",
    "camera 360 protech 10",
    "camera 360",
    "camera 360 giá sau bạn",
    "cho mình hỏi giá camera 360",
    "xin giá camera 360",
    "camera 360 giá bnh shop",
    "xin giá camera 360",
    "giá camera 360 shop",
    "Camera 360 DCTECH giá bao nhiêu?",
    "Góc quay camera có rộng không?",
    "Thời gian lắp đặt camera 360 mất bao lâu?",
    "Lái xe số sàn có cần camera 360 không em?",
    "Camera 360 có quay được ban đêm không?",
    "Camera DCTECH dùng được với màn hình nào?",
    "Camera 360 lắp lên có ảnh hưởng điện xe không?",
    "tư vấn camera 360",
    "cho mình thông tin camera 360",
    "tư vấn camera 360",
    "camera 360 có tính năng gì shop",
    "xin thông tin camera 360",
    "tư vấn camera 360 shop",
    "camera 360 cho xe có dùng được cho màn hình zin cx5 2025 k",
    "camera 360 dc b300 có dùng đc cho vf9 không shop",
    "mercedes c200 2015 có dùng được camera 360 ko?",
    "Camera 360 lắp lên có ảnh hưởng điện xe không?",
    "Camera DCTECH dùng được với màn hình nào?",
    "Camera 360 có quay được ban đêm không?",
    "Lái xe số sàn có cần camera 360 không em?",
    "Thời gian lắp đặt camera 360 mất bao lâu?",
    "Góc quay camera có rộng không?",
]

brandInfoSamples = [
    "dctech là gì vậy em?",
    "dctech có những dòng sản phẩm nào?",
    "dctech có cửa hàng ở đâu vậy em?",
    "dctech có hỗ trợ lắp đặt không?",
    "dctech có bảo hành không?",
    "dctech có hỗ trợ trả góp không?",
    "dctech có hỗ trợ lắp đặt tận nơi không?",
    "dctech có hỗ trợ lắp đặt ở tỉnh không?",
    "chính sách bảo hành của dctech như thế nào?",
    "dctech có những ưu đãi gì không?",
    "dctech có hỗ trợ kỹ thuật sau khi lắp đặt không?",
    "chính sách bảo hành",
    "hệ sinh thái của dctech",
    "giới thiệu về dctech",
    "dctech là gì",
    "dctech là thương hiệu nào?",
    "dctech làm gì",
    "shop có những sản phẩm nào",
    "bên em có những sản phẩm nào",
    "có những sản phẩm nào",
]   


clarifySamples = [
    "Xin giá",
    "Xin gia",
    "Xin giá shop",
    "Giá",
    "Giá chính sác bao nhiêu",
    "Báo giá",
    "Báo giá sản phẩm",
    "bn",
    "giá bn",
    "giá bn v ạ",
    "gia nhiu vay",
    "giá sản phẩm",
    "cho xinh giá",
    "cho xin giá",
    "Xin giá sp",
    "giá thế nào shop",
    "giá sao a",
    "Cho mình xin giá tham khảo",
    "xin chào",
    "xin chào shop",
    "hi",
    "hello",
    "tư vấn",
]